const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, authorization","Access-Control-Allow-Methods":"GET,POST,PUT,DELETE,OPTIONS"};
const enc=new TextEncoder();
const out=(x,s=200)=>Response.json(x,{status:s,headers:cors});
const hash=async s=>{const b=await crypto.subtle.digest("SHA-256",enc.encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")};
const money=v=>Math.round(Number(v||0)*100);
const unitFactor={g:1,kg:1000,ml:1,l:1000,un:1};
const convertQty=(q,from,to)=>{if(from===to)return Number(q||0);if(!unitFactor[from]||!unitFactor[to])return null;const familyA=(from==="g"||from==="kg"),familyB=(to==="g"||to==="kg"),familyC=(from==="ml"||from==="l"),familyD=(to==="ml"||to==="l");if((familyA&&!familyB)||(familyB&&!familyA)||(familyC&&!familyD)||(familyD&&!familyC))return null;return Number(q||0)*unitFactor[from]/unitFactor[to]};
async function init(env){
 await env.DB.batch([
  env.DB.prepare("CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'operator',active INTEGER NOT NULL DEFAULT 1)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT,price_cents INTEGER DEFAULT 0,cost_cents INTEGER DEFAULT 0,stock REAL DEFAULT 0,min_stock REAL DEFAULT 0,active INTEGER DEFAULT 1)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,address TEXT,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER,status TEXT DEFAULT 'pending',payment_method TEXT,total_cents INTEGER DEFAULT 0,delivery_fee_cents INTEGER DEFAULT 0,notes TEXT,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,product_id INTEGER,quantity REAL,unit_price_cents INTEGER,unit_cost_cents INTEGER)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,description TEXT,amount_cents INTEGER,category TEXT,paid_at TEXT,notes TEXT,created_by INTEGER)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS stock_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER,quantity REAL,type TEXT,reason TEXT,reference_id INTEGER,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS cash_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT,description TEXT,amount_cents INTEGER,payment_method TEXT,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id INTEGER,expires_at TEXT)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS recipes(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER UNIQUE NOT NULL,yield_qty REAL DEFAULT 1,yield_unit TEXT DEFAULT 'unidade',created_at TEXT DEFAULT CURRENT_TIMESTAMP)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS recipe_items(id INTEGER PRIMARY KEY AUTOINCREMENT,recipe_id INTEGER NOT NULL,ingredient_id INTEGER NOT NULL,quantity REAL NOT NULL,quantity_unit TEXT DEFAULT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)"),
  env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_recipe_items_recipe ON recipe_items(recipe_id)"),
  env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_recipe_items_ingredient ON recipe_items(ingredient_id)")
 ]);
 for(const sql of [
  "ALTER TABLE recipe_items ADD COLUMN quantity_unit TEXT DEFAULT NULL",
  "ALTER TABLE products ADD COLUMN product_type TEXT DEFAULT 'sale'",
  "ALTER TABLE products ADD COLUMN base_unit TEXT DEFAULT 'un'",
  "ALTER TABLE products ADD COLUMN purchase_qty REAL DEFAULT 0",
  "ALTER TABLE products ADD COLUMN purchase_unit TEXT DEFAULT 'un'",
  "ALTER TABLE products ADD COLUMN purchase_cost_cents INTEGER DEFAULT 0",
  "ALTER TABLE products ADD COLUMN yield_percent REAL DEFAULT 100",
  "ALTER TABLE products ADD COLUMN unit_cost_micros INTEGER DEFAULT 0"
 ]){try{await env.DB.prepare(sql).run()}catch{}}

 const n=await env.DB.prepare("SELECT COUNT(*) n FROM users").first();
 if(!n.n){const adminPass=env.ADMIN_PASSWORD||"1234";const caixaPass=env.CAIXA_PASSWORD||"1234";await env.DB.prepare("INSERT INTO users(username,password_hash,role) VALUES(?,?,?)").bind("admin",await hash(adminPass),"admin").run();await env.DB.prepare("INSERT INTO users(username,password_hash,role) VALUES(?,?,?)").bind("caixa",await hash(caixaPass),"operator").run()}
}
async function user(req,env){
 const h=req.headers.get("authorization")||"";
 if(!h.startsWith("Bearer "))return null;
 const t=await hash(h.slice(7));
 return env.DB.prepare("SELECT u.id,u.username,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND u.active=1 AND s.expires_at>datetime('now')").bind(t).first();
}
async function login(req,env){
 const b=await req.json();
 const username=String(b.username||"").trim().toLowerCase();
 const password=String(b.password||"");
 if(!username||!password)return out({error:"Informe usuário e senha"},400);
 const u=await env.DB.prepare("SELECT * FROM users WHERE lower(username)=? AND active=1").bind(username).first();
 if(!u||await hash(password)!==u.password_hash)return out({error:"Usuário ou senha inválidos"},401);
 await env.DB.prepare("DELETE FROM sessions WHERE expires_at<=datetime('now')").run();
 const bytes=crypto.getRandomValues(new Uint8Array(32));
 const token=[...bytes].map(x=>x.toString(16).padStart(2,"0")).join("");
 await env.DB.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,datetime('now','+7 days'))").bind(await hash(token),u.id).run();
 return out({token,user:{id:u.id,username:u.username,role:u.role}});
}
export default {async fetch(req,env){
 if(req.method==="OPTIONS")return new Response(null,{headers:cors});
 const u=new URL(req.url);
 try{
  if(u.pathname==="/api/health")return out({ok:true,database:!!env.DB});
  if(!env.DB)return out({error:"D1 não configurado"},503);
  await init(env);
  if(u.pathname==="/api/auth/register"&&req.method==="POST"){const b=await req.json();const n=String(b.username||"").trim().toLowerCase();const p=String(b.password||"");if(n.length<3||p.length<4)return out({error:"Usuário ou senha inválidos"},400);const x=await env.DB.prepare("SELECT id FROM users WHERE username=?").bind(n).first();if(x)return out({error:"Usuário já cadastrado"},409);await env.DB.prepare("INSERT INTO users(username,password_hash,role,active) VALUES(?,?,?,1)").bind(n,await hash(p),"operator").run();return out({ok:true},201)}
  if(u.pathname==="/api/auth/login"&&req.method==="POST")return login(req,env);
  const me=await user(req,env);if(!me)return out({error:"Não autenticado"},401);
  if(u.pathname==="/api/auth/me")return out({user:me});
  if(u.pathname==="/api/auth/logout"){const h=req.headers.get("authorization")||"";if(h.startsWith("Bearer "))await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await hash(h.slice(7))).run();return out({ok:true})}
  if(u.pathname==="/api/dashboard"){const m=u.searchParams.get("month")||new Date().toISOString().slice(0,7);const s=await env.DB.prepare("SELECT COALESCE(SUM(total_cents),0) v,COUNT(*) n FROM orders WHERE status!='cancelled' AND substr(created_at,1,7)=?").bind(m).first();const e=await env.DB.prepare("SELECT COALESCE(SUM(amount_cents),0) v FROM expenses WHERE substr(paid_at,1,7)=?").bind(m).first();const low=await env.DB.prepare("SELECT COUNT(*) n FROM products WHERE active=1 AND stock<=min_stock").first();return out({sales_cents:s.v,orders:s.n,expenses_cents:e.v,profit_cents:Number(s.v)-Number(e.v),low_stock:low.n});}
  if(u.pathname==="/api/products"&&req.method==="GET")return out((await env.DB.prepare("SELECT * FROM products WHERE active=1 ORDER BY name").all()).results);
  if(u.pathname==="/api/products"&&req.method==="POST"){const b=await req.json();const type=b.product_type||"sale",base=b.base_unit||"un",purchaseQty=Number(b.purchase_qty||0),purchaseCost=money(b.purchase_cost),yieldPct=Math.max(0,Number(b.yield_percent||100));const effectiveQty=purchaseQty*(yieldPct/100);const unitMicros=effectiveQty>0?Math.round((purchaseCost/100)*1000000/effectiveQty):0;const derivedCost=Math.round(unitMicros/10000);const r=await env.DB.prepare("INSERT INTO products(name,category,price_cents,cost_cents,stock,min_stock,product_type,base_unit,purchase_qty,purchase_unit,purchase_cost_cents,yield_percent,unit_cost_micros) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(b.name,b.category||"",money(b.price),derivedCost,Number(b.stock||0),Number(b.min_stock||0),type,base,purchaseQty,b.purchase_unit||base,purchaseCost,yieldPct,unitMicros).run();return out({id:r.meta.last_row_id,cost_cents:derivedCost,unit_cost_micros:unitMicros},201)}
  if(u.pathname==="/api/recipes"&&req.method==="GET"){const pid=Number(u.searchParams.get("product_id")||0);if(!pid)return out([]);const r=await env.DB.prepare("SELECT r.*,p.name product_name FROM recipes r JOIN products p ON p.id=r.product_id WHERE r.product_id=?").bind(pid).first();if(!r)return out(null);const items=(await env.DB.prepare("SELECT ri.*,p.name ingredient_name,p.base_unit,p.unit_cost_micros,p.purchase_qty,p.purchase_unit,p.purchase_cost_cents FROM recipe_items ri JOIN products p ON p.id=ri.ingredient_id WHERE ri.recipe_id=? ORDER BY ri.id").bind(r.id).all()).results;const cost=items.reduce((s,i)=>s+Math.round(Number(i.quantity)*Number(i.unit_cost_micros||0)),0);return out({...r,items:items.map(i=>({...i,used_unit:i.quantity_unit||i.base_unit||"un"})),cost_micros:cost,cost_cents:Math.round(cost/10000),cost_reais:cost/1000000})}
  if(u.pathname==="/api/recipes"&&req.method==="POST"){const b=await req.json();const pid=Number(b.product_id);if(!pid||!Array.isArray(b.items)||!b.items.length)return out({error:"Informe o produto e os ingredientes"},400);const product=await env.DB.prepare("SELECT * FROM products WHERE id=? AND active=1").bind(pid).first();if(!product)return out({error:"Produto não encontrado"},404);const items=[];for(const i of b.items){const ing=await env.DB.prepare("SELECT * FROM products WHERE id=? AND active=1").bind(Number(i.ingredient_id)).first();const q=Number(i.quantity),u=i.quantity_unit||ing?.base_unit||"un",normalized=ing?convertQty(q,u,ing.base_unit||"un"):null;if(!ing||ing.id===pid||q<=0||normalized===null)return out({error:"Ingrediente inválido ou unidade incompatível"},400);items.push([ing,normalized,u])}const old=await env.DB.prepare("SELECT id FROM recipes WHERE product_id=?").bind(pid).first();let rid;if(old){rid=old.id;await env.DB.prepare("UPDATE recipes SET yield_qty=?,yield_unit=? WHERE id=?").bind(Number(b.yield_qty||1),b.yield_unit||"unidade",rid).run();await env.DB.prepare("DELETE FROM recipe_items WHERE recipe_id=?").bind(rid).run()}else{const rr=await env.DB.prepare("INSERT INTO recipes(product_id,yield_qty,yield_unit) VALUES(?,?,?)").bind(pid,Number(b.yield_qty||1),b.yield_unit||"unidade").run();rid=rr.meta.last_row_id}for(const [ing,q,u] of items)await env.DB.prepare("INSERT INTO recipe_items(recipe_id,ingredient_id,quantity,quantity_unit) VALUES(?,?,?,?)").bind(rid,ing.id,q,u).run();const total=items.reduce((s,[ing,q])=>s+Math.round(q*Number(ing.unit_cost_micros||0)),0);const per=Number(b.yield_qty||1)>0?Math.round(total/Number(b.yield_qty||1)):total;await env.DB.prepare("UPDATE products SET cost_cents=? WHERE id=?").bind(Math.round(per/10000),pid).run();return out({ok:true,recipe_id:rid,cost_micros:total,cost_cents:Math.round(per/10000),cost_reais:per/1000000},201)}
  if(u.pathname==="/api/customers"&&req.method==="GET")return out((await env.DB.prepare("SELECT * FROM customers ORDER BY name").all()).results);
  if(u.pathname==="/api/customers"&&req.method==="POST"){const b=await req.json();const r=await env.DB.prepare("INSERT INTO customers(name,phone,address,notes) VALUES(?,?,?,?)").bind(b.name,b.phone||"",b.address||"",b.notes||"").run();return out({id:r.meta.last_row_id},201)}
  if(u.pathname==="/api/orders"&&req.method==="GET")return out((await env.DB.prepare("SELECT o.*,c.name customer_name FROM orders o LEFT JOIN customers c ON c.id=o.customer_id ORDER BY o.id DESC").all()).results);
  if(u.pathname==="/api/orders"&&req.method==="POST"){const b=await req.json();if(!Array.isArray(b.items)||!b.items.length)return out({error:"Adicione itens ao pedido"},400);let total=money(b.delivery_fee);const items=[];for(const i of b.items){const p=await env.DB.prepare("SELECT * FROM products WHERE id=? AND active=1").bind(i.product_id).first();const q=Number(i.quantity);if(!p||q<=0)return out({error:"Produto inválido"},400);if(Number(p.stock)<q)return out({error:"Estoque insuficiente: "+p.name},400);if(p.product_type==="sale"||p.product_type==="production"){const rec=await env.DB.prepare("SELECT * FROM recipes WHERE product_id=?").bind(p.id).first();if(rec){const ri=(await env.DB.prepare("SELECT ri.*,p.name ingredient_name,p.base_unit FROM recipe_items ri JOIN products p ON p.id=ri.ingredient_id WHERE ri.recipe_id=?").bind(rec.id).all()).results;for(const x of ri){const consume=Number(x.quantity)*q/Math.max(1,Number(rec.yield_qty||1));const ing=await env.DB.prepare("SELECT * FROM products WHERE id=? AND active=1").bind(x.ingredient_id).first();if(!ing||Number(ing.stock)<consume)return out({error:"Estoque insuficiente do insumo: "+(ing?.name||x.ingredient_name)},400)}}}total+=p.price_cents*q;items.push([p,q])}const o=await env.DB.prepare("INSERT INTO orders(customer_id,status,payment_method,total_cents,delivery_fee_cents,notes,created_by) VALUES(?,?,?,?,?,?,?)").bind(b.customer_id||null,b.status||"pending",b.payment_method||"pix",total,money(b.delivery_fee),b.notes||"",me.id).run();for(const [p,q] of items){await env.DB.prepare("INSERT INTO order_items(order_id,product_id,quantity,unit_price_cents,unit_cost_cents) VALUES(?,?,?,?,?)").bind(o.meta.last_row_id,p.id,q,p.price_cents,p.cost_cents).run();await env.DB.prepare("UPDATE products SET stock=stock-? WHERE id=?").bind(q,p.id).run();await env.DB.prepare("INSERT INTO stock_movements(product_id,quantity,type,reason,reference_id,created_by) VALUES(?,?,?,?,?,?)").bind(p.id,-q,"sale","Pedido #"+o.meta.last_row_id,o.meta.last_row_id,me.id).run();if(p.product_type==="sale"||p.product_type==="production"){const rec=await env.DB.prepare("SELECT * FROM recipes WHERE product_id=?").bind(p.id).first();if(rec){const ri=(await env.DB.prepare("SELECT * FROM recipe_items WHERE recipe_id=?").bind(rec.id).all()).results;for(const x of ri){const consume=Number(x.quantity)*q/Math.max(1,Number(rec.yield_qty||1));await env.DB.prepare("UPDATE products SET stock=stock-? WHERE id=?").bind(consume,x.ingredient_id).run();await env.DB.prepare("INSERT INTO stock_movements(product_id,quantity,type,reason,reference_id,created_by) VALUES(?,?,?,?,?,?)").bind(x.ingredient_id,-consume,"recipe_use","Pedido #"+o.meta.last_row_id,o.meta.last_row_id,me.id).run()}}}}await env.DB.prepare("INSERT INTO cash_movements(type,description,amount_cents,payment_method,created_by) VALUES(?,?,?,?,?)").bind("in","Pedido #"+o.meta.last_row_id,total,b.payment_method||"pix",me.id).run();return out({id:o.meta.last_row_id,total_cents:total},201);}
  if(u.pathname==="/api/expenses"&&req.method==="GET")return out((await env.DB.prepare("SELECT * FROM expenses ORDER BY id DESC").all()).results);
  if(u.pathname==="/api/expenses"&&req.method==="POST"){const b=await req.json(),a=money(b.amount);const r=await env.DB.prepare("INSERT INTO expenses(description,amount_cents,category,paid_at,notes,created_by) VALUES(?,?,?,?,?,?)").bind(b.description,a,b.category||"geral",b.paid_at||new Date().toISOString().slice(0,10),b.notes||"",me.id).run();await env.DB.prepare("INSERT INTO cash_movements(type,description,amount_cents,payment_method,created_by) VALUES(?,?,?,?,?)").bind("out",b.description,a,b.payment_method||"pix",me.id).run();return out({id:r.meta.last_row_id},201)}
  if(u.pathname==="/api/stock"&&req.method==="POST"){const b=await req.json();await env.DB.prepare("UPDATE products SET stock=stock+? WHERE id=?").bind(Number(b.quantity),b.product_id).run();await env.DB.prepare("INSERT INTO stock_movements(product_id,quantity,type,reason,created_by) VALUES(?,?,?,?,?)").bind(b.product_id,Number(b.quantity),"in",b.reason||"entrada",me.id).run();return out({ok:true},201)}
  if(u.pathname==="/api/cash"&&req.method==="GET")return out((await env.DB.prepare("SELECT * FROM cash_movements ORDER BY id DESC").all()).results);
  if(u.pathname==="/api/reports"){const a=u.searchParams.get("from")||"2000-01-01",b=u.searchParams.get("to")||"2999-12-31";const s=await env.DB.prepare("SELECT COALESCE(SUM(total_cents),0) v,COUNT(*) n FROM orders WHERE status!='cancelled' AND date(created_at) BETWEEN ? AND ?").bind(a,b).first();const e=await env.DB.prepare("SELECT COALESCE(SUM(amount_cents),0) v FROM expenses WHERE date(paid_at) BETWEEN ? AND ?").bind(a,b).first();return out({sales_cents:s.v,orders:s.n,expenses_cents:e.v,profit_cents:Number(s.v)-Number(e.v)})}
  return out({error:"Rota não encontrada"},404);
 }catch(e){return out({error:e.message||"Erro interno"},500)}
}}